version: '3'

services:
  api:
    image: app
    working_dir: /code
    volumes:
      - ..:/code
    depends_on:
      - db
    ports:
      - "8000:8000"
    build:
      context: .
    command: ./develop/wait-for-it.sh db:5432 -- ./.bin/app
    networks:
      - app

  db:
    image: "postgres:10.6"
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: testpassword
    volumes:
      - pgdata_personal:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

  migrate:
    image: app
    build:
      context: .
    command: ./develop/wait-for-it.sh db:5432 -- bash ./migrations/dev-migrate.sh
    working_dir: /code
    volumes:
      - ..:/code
    depends_on:
      - db
    networks:
      - app

  migrate-down:
    image: app
    build:
      context: .
    command: ./develop/wait-for-it.sh db:5432 -- bash ./migrations/dev-migrate-down.sh
    working_dir: /code
    volumes:
      - ..:/code
    depends_on:
      - db
    networks:
      - app

volumes:
  pgdata_personal:

networks:
  app:
